### ISSUE TITLE
Invalid argument argument error in RandomIO

### ISSUE THREAD

**Issue by F483** [Storj/dataserv-client#102]
pthalodezin 6:34 PM prior to that I was getting an error every 300-500 shards
was that a part of the fix you were previously handling
Traceback (most recent call last):
 File "dataserv-client", line 10, in <module>
 File "E:\dataserv-client\dataserv_client\cli.py", line 153, in main
 File "E:\dataserv-client\dataserv_client\api.py", line 174, in build
 File "E:\dataserv-client\dataserv_client\builder.py", line 110, in build
 File "E:\dataserv-client\dataserv_client\builder.py", line 57, in generate_shard
 File "C:\Python34\lib\site-packages\RandomIO\RandomIO.py", line 211, in genfile
 File "C:\Python34\lib\site-packages\RandomIO\RandomIO.py", line 187, in dump
OSError: [Errno 22] Invalid argument

**Comment by F483** [comment]
Additional info from pthalodezin

OS: windows 10 64bit
dataserv-client: 2.0.3
command: `dataserv-client.exe  --store_path Y:\FARM6 --max_size 14T --url http://status.driveshare.org:5000 --debug build` and `dataserv-client.exe --set_interval_height 10000  --store_path Y:\FARM6 --max_size 14T --url http://status.driveshare.org:5000 --debug build`

**Comment by littleskunk** [comment]
dataserv-client.exe --set_interval_height 10000 --store_path Y:\FARM6 --max_size 14T --url http://status.driveshare.org:5000 --debug build

Should cause a exception. --set_height_interval and it has to stay behind build. The other command should be fine.

Why is dataserv-client in a different root directory than RandomIO? Looks like a diry installation. Old version of crypto or binascii could be the reason for the bug.

**Comment by F483** [comment]
Sorry that was a mistake of mine in reporting the bug, fixed the message.

**Comment by littleskunk** [comment]
@F483 please close the issue. I gues its duplicate https://github.com/Storj/dataserv-client/issues/108
