### ISSUE TITLE
InvalidAddress errors reported by several users.

### ISSUE THREAD

**Issue by F483** [Storj/dataserv-client#103]
crypto_n8 9:10 PM sure thing
9:10
C:\dataserv-client>dataserv-client.exe --debug --url http://status.driveshare.org:5000 register
Traceback (most recent call last):
 File "E:\dataserv-client\dataserv_client\messaging.py", line 45, in _url_query
 File "C:\Python34\lib\urllib\request.py", line 161, in urlopen
 File "C:\Python34\lib\urllib\request.py", line 469, in open
 File "C:\Python34\lib\urllib\request.py", line 579, in http_response
 File "C:\Python34\lib\urllib\request.py", line 507, in error
 File "C:\Python34\lib\urllib\request.py", line 441, in _call_chain
 File "C:\Python34\lib\urllib\request.py", line 587, in http_error_default
urllib.error.HTTPError: HTTP Error 400: BAD REQUESTDuring handling of the above exception, another exception occurred:Traceback (most recent call last):
 File "dataserv-client", line 10, in <module>
 File "E:\dataserv-client\dataserv_client\cli.py", line 153, in main
 File "E:\dataserv-client\dataserv_client\api.py", line 72, in register
 File "E:\dataserv-client\dataserv_client\messaging.py", line 100, in register
 File "E:\dataserv-client\dataserv_client\messaging.py", line 55, in _url_query
dataserv_client.exceptions.InvalidAddress: Address 1JY7zksfi9t6z5v7S6T7KRuHu37Anzr3rR not valid!

**Comment by F483** [comment]
Mark-Mayers-MacBook-Pro:dataserv-client mark$ dataserv-client --store_path /Volumes/Drobo/ --url http://status.driveshare.org:5000 --max_size 2958158725120 --debug build --set_height_interval 100
Resuming from height 11799
Saving seed 1594ae56145baff08f9e2f763eba5631628f4fe2390c36cfb0bec9c48915962e with SHA-256 hash c97131f4f8e04abaab09f9586391760c744f3663328a0cf8b51db396316a590d.
Saving seed 4fe48480270fcbf24dbba4c4de63fd1a542a218667539d8fc90bdbbe3cb96c2b with SHA-256 hash 11d00877c909a31b39c44285671b1b1dc5554b271333506c3d0aaf72cc472f3b.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/dataserv_client-2.0.3-py3.4.egg/dataserv_client/messaging.py", line 45, in _url_query
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 469, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 507, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 587, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: BAD REQUEST

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/dataserv-client", line 4, in <module>
    __import__('pkg_resources').run_script('dataserv-client==2.0.3', 'dataserv-client')
  File "/usr/local/lib/python3.4/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1659, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.4/site-packages/dataserv_client-2.0.3-py3.4.egg/EGG-INFO/scripts/dataserv-client", line 10, in <module>
  File "/usr/local/lib/python3.4/site-packages/dataserv_client-2.0.3-py3.4.egg/dataserv_client/cli.py", line 153, in main
  File "/usr/local/lib/python3.4/site-packages/dataserv_client-2.0.3-py3.4.egg/dataserv_client/api.py", line 174, in build
  File "/usr/local/lib/python3.4/site-packages/dataserv_client-2.0.3-py3.4.egg/dataserv_client/builder.py", line 118, in build
  File "/usr/local/lib/python3.4/site-packages/dataserv_client-2.0.3-py3.4.egg/dataserv_client/api.py", line 166, in _on_generate_shard
  File "/usr/local/lib/python3.4/site-packages/dataserv_client-2.0.3-py3.4.egg/dataserv_client/messaging.py", line 115, in height
  File "/usr/local/lib/python3.4/site-packages/dataserv_client-2.0.3-py3.4.egg/dataserv_client/messaging.py", line 55, in _url_query
dataserv_client.exceptions.InvalidAddress: Address 1L8TqPgh2zi2V3n2oJx2WgqxUF3bTumErk not valid!

**Comment by nrenich** [comment]
Also, using:
```
C:\dataserv-client>dataserv-client.exe --debug --url http://status.driveshare.org:5000 config
```
reports the proper/same information from the initial setup on 2.0.3.

**Comment by linuxman21** [comment]
yep, cant poll or register at the moment. getting the same dataserv_client.exceptions.InvalidAddress:  error when trying to register

**Comment by F483** [comment]
Server address validation function was broken, changed to address validation function of btctxstore.
