### ISSUE TITLE
Many users reporting on 2.0.0+ server HTTP Error 500: INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by ironsf** [Storj/dataserv-client#105]
i am running: ubuntu 14.04, dataserv-client 2.0.3
after more then 10 hours of build (aprox 1,5tb done) command i get this:
<blockquote>Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/messaging.py", line 45, in _url_query
    response = urllib.request.urlopen(req)
  File "/usr/lib/python3.4/urllib/request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: INTERNAL SERVER ERROR

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/dataserv-client", line 10, in <module>
    cli.main(sys.argv[1:])
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/cli.py", line 153, in main
    return getattr(client, command_name)(**arguments)
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/api.py", line 174, in build
    rebuild=rebuild)
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/builder.py", line 118, in build
    self.on_generate_shard(shard_num + 1, seed, file_hash)
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/api.py", line 166, in _on_generate_shard
    self.messenger.height(cur_height)
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/messaging.py", line 115, in height
    height))
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/messaging.py", line 57, in _url_query
    raise exceptions.FarmerError(self._server_url)
dataserv_client.exceptions.FarmerError: Farmer error at http://status.driveshare.org:5000!
</blockquote>

**Comment by F483** [comment]
slackman 5:57 PM I'm using version 2.0.3 of dataserv-client on Ubuntu and after a little time I launched the poll get the following error: Traceback (most recent call last):
 File "/usr/local/lib/python3.4/dist-packages/dataserv_client/messaging.py", line 45, in _url_query
   response = urllib.request.urlopen(req)
 File "/usr/lib/python3.4/urllib/request.py", line 153, in urlopen
   return opener.open(url, data, timeout)
 File "/usr/lib/python3.4/urllib/request.py", line 461, in open
   response = meth(req, response)
 File "/usr/lib/python3.4/urllib/request.py", line 571, in http_response
   'http', request, response, code, msg, hdrs)
 File "/usr/lib/python3.4/urllib/request.py", line 499, in error
   return self._call_chain(*args)
 File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
   result = func(*args)
 File "/usr/lib/python3.4/urllib/request.py", line 579, in http_error_default
   raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: INTERNAL SERVER ERRORDuring handling of the above exception, another exception occurred:Traceback (most recent call last):
 File "/usr/local/bin/dataserv-client", line 10, in <module>
   cli.main(sys.argv[1:])
 File "/usr/local/lib/python3.4/dist-packages/dataserv_client/cli.py", line 153, in main
   return getattr(client, command_name)(**arguments)
 File "/usr/local/lib/python3.4/dist-packages/dataserv_client/api.py", line 135, in poll
   self.ping()
 File "/usr/local/lib/python3.4/dist-packages/dataserv_client/api.py", line 115, in ping
   self.messenger.ping()
 File "/usr/local/lib/python3.4/dist-packages/dataserv_client/messaging.py", line 110, in ping
   return self._url_query("/api/ping/%s" % self.auth_address())
 File "/usr/local/lib/python3.4/dist-packages/dataserv_client/messaging.py", line 57, in _url_query
   raise exceptions.FarmerError(self._server_url)
dataserv_client.exceptions.FarmerError: Farmer error at http://status.driveshare.org:5000!

**Comment by F483** [comment]
These seem to have been uncaught auth errors, fixed in https://github.com/Storj/dataserv/commit/36eac2e86ad9de5574c86b7770dbc9ba97a47feb
