### ISSUE TITLE
v2.0.3 client dropped from :5000 server list

### ISSUE THREAD

**Issue by heunland** [Storj/dataserv-client#106]
I am polling a client on windows 7 using an external FAT32 formatted HDD. The polling was working fine and my address correctly showed up in http://status.driveshare.org:5000/api/online list but it suddenly completely disappeared from the list without showing any error log in my command window, where it appears like the client still continues to ping:
polling command used: 
dataserv-client --url=http://status.driveshare.org:5000 poll
now shown in command window:
Pinging http://status.driveshare.org:5000 with address 1H1kVNsBtpE7i9y2enkZkhtZN3kQp6otKX. 
However, the command window is unresponsive and does not let me abort the pinging unless I force close the window completely.

Other users appeared to experience similar issues. 

I tried to restart polling after force closing the window and opening a new one. I got an error window appear on my screen saying "there is no disk in the drive. Insert a disk in drive \Device\Harddisk1\DR1" and also in the command window it gives me this traceback:

  File "E:\dataserv-client\dataserv_client\messaging.py", line 45, in _url_query

  File "C:\Python34\lib\urllib\request.py", line 161, in urlopen
  File "C:\Python34\lib\urllib\request.py", line 469, in open
  File "C:\Python34\lib\urllib\request.py", line 579, in http_response
  File "C:\Python34\lib\urllib\request.py", line 507, in error
  File "C:\Python34\lib\urllib\request.py", line 441, in _call_chain
  File "C:\Python34\lib\urllib\request.py", line 587, in http_error_default
urllib.error.HTTPError: HTTP Error 400: BAD REQUEST

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dataserv-client", line 10, in <module>
  File "E:\dataserv-client\dataserv_client\cli.py", line 153, in main
  File "E:\dataserv-client\dataserv_client\api.py", line 135, in poll
  File "E:\dataserv-client\dataserv_client\api.py", line 115, in ping
  File "E:\dataserv-client\dataserv_client\messaging.py", line 110, in ping
  File "E:\dataserv-client\dataserv_client\messaging.py", line 55, in _url_query

dataserv_client.exceptions.InvalidAddress: Address 1H1kVNsBtpE7i9y2enkZkhtZN3kQp
6otKX not valid!

I was trying to poll an address that was previously registered and built. 

Attempt to reregister resulted in the same error: Error window appear on my screen saying "there is no disk in the drive. Insert a disk in drive \Device\Harddisk1\DR1" and also in the command window it gives me this traceback:

Traceback (most recent call last):
  File "E:\dataserv-client\dataserv_client\messaging.py", line 45, in _url_query

  File "C:\Python34\lib\urllib\request.py", line 161, in urlopen
  File "C:\Python34\lib\urllib\request.py", line 469, in open
  File "C:\Python34\lib\urllib\request.py", line 579, in http_response
  File "C:\Python34\lib\urllib\request.py", line 507, in error
  File "C:\Python34\lib\urllib\request.py", line 441, in _call_chain
  File "C:\Python34\lib\urllib\request.py", line 587, in http_error_default
urllib.error.HTTPError: HTTP Error 400: BAD REQUEST

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dataserv-client", line 10, in <module>
  File "E:\dataserv-client\dataserv_client\cli.py", line 153, in main
  File "E:\dataserv-client\dataserv_client\api.py", line 72, in register
  File "E:\dataserv-client\dataserv_client\messaging.py", line 100, in register
  File "E:\dataserv-client\dataserv_client\messaging.py", line 55, in _url_query

dataserv_client.exceptions.InvalidAddress: Address 1H1kVNsBtpE7i9y2enkZkhtZN3kQp
6otKX not valid!

**Comment by heunland** [comment]
After #103 issue fix, I was able to reregister, rebuild and poll using nic´s instructions in #general. However, only rebuilt to the same height (11022) I had before since the FAT32 formatted drive I am using doesn´t allow me to build any higher as previously reported in issue #81

**Comment by littleskunk** [comment]
Found the bug on the server. It should ignore pings faster than 15 sec but it did the oposit. If you missed one ping or need more than 15 sec the server ignored every incoming ping. Only way to be on the online list was to register and imidiate ping faster than 15 sec and never stop pinging.

I gues a server restart is needed. I hope we see everyone online again soon :)

**Comment by F483** [comment]
Fixed by @littleskunk in https://github.com/Storj/dataserv/pull/43
