### ISSUE TITLE
OSError on build

### ISSUE THREAD

**Issue by F483** [Storj/dataserv-client#108]
pthalodezin 12:59 PM I keep getting 

Traceback (most recent call last):
File "dataserv-client", line 10, in <module>
File "E:\dataserv-client\dataserv_client\cli.py", line 153, in main
File "E:\dataserv-client\dataserv_client\api.py", line 174, in build
File "E:\dataserv-client\dataserv_client\builder.py", line 110, in build
File "E:\dataserv-client\dataserv_client\builder.py", line 61, in generate_shard
OSError: [Errno 22] Invalid argument
v2..0.3
win10 64b
dataserv-client.exe --config_path C:\Users\pthalodezin\.storj\config7.json --store_path Z:/FARM7 --max_size 7T --url http://status.driveshare.org:5000 --debug build --set_height_interval 10000
handles about 90-100 shards before error

**Comment by F483** [comment]
@littleskunk can you confirm this? I have the feeling this may be some windows issue.

**Comment by littleskunk** [comment]
I was able to get the exception as well. pthalodezin is using a networkdrive. I did the same but i disconected the drive for a short moment and than i get the same excetion. RandomIO line 187 IOError: [Errno 22] Invalid argument

**Comment by littleskunk** [comment]
@F483 some more information:
http://stackoverflow.com/questions/11662960/ioerror-errno-22-invalid-argument-when-reading-writing-large-bytestring

For now i dont know how to fix it. I hope it will work with python 2.7:
https://www.python.org/downloads/release/python-2710/
http://www.microsoft.com/en-us/download/details.aspx?id=44266

**Comment by pthalodezin** [comment]
Two hours running python on 3 simultaneous builds (all on network drives) Only one instance of 401 error.  That's down from 2-5 per hour on each build.  Error occurs in polling (also running 3 simultaneously)
Pinging http://status.driveshare.org:5000 with address 1B54YifADnM5XuxXiZQF5hnJm6E5yeMNGi.
Pinging http://status.driveshare.org:5000 with address 1B54YifADnM5XuxXiZQF5hnJm6E5yeMNGi.
Traceback (most recent call last):
  File "Scripts\dataserv-client", line 10, in <module>
    cli.main(sys.argv[1:])
  File "c:\Python27\lib\site-packages\dataserv_client\cli.py", line 153, in main
    return getattr(client, command_name)(**arguments)
  File "c:\Python27\lib\site-packages\dataserv_client\api.py", line 135, in poll
    self.ping()
  File "c:\Python27\lib\site-packages\dataserv_client\api.py", line 115, in ping
    self.messenger.ping()
  File "c:\Python27\lib\site-packages\dataserv_client\messaging.py", line 110, in ping
    return self._url_query("/api/ping/%s" % self.auth_address())
  File "c:\Python27\lib\site-packages\dataserv_client\messaging.py", line 59, in _url_query
    raise e  # pragma: no cover
future.backports.urllib.error.HTTPError: HTTP Error 401: UNAUTHORIZED

**Comment by littleskunk** [comment]
@pthalodezin 
Keep it running. As long as you dont get any IOError: [Errno 22] Invalid argument it looks good.

The 401 exception is a known bug and has other reasons. Please sync you clock with the internet. The Server allows only 15 sec difference.

**Comment by pthalodezin** [comment]
Haven't seen anymore IOErrors, just dealing with the 401 now
THey are infrequent and aren't causing too many headaches at the present time

**Comment by littleskunk** [comment]
https://github.com/Storj/dataserv-client/issues/111

**Comment by littleskunk** [comment]
We still need a bugfix. We only confirmed that Python 3 has problems with large byte files. 

Next step will be a test with Python 3 and open(file, 'w') maybe that will fix the bug.

**Comment by pthalodezin** [comment]
Saving seed bd6eda34f8aa635cf5838ee38f7c4e33a731cf5a5c5a3c59cf3fcca836c9132d with SHA-256 hash 3cb01b798ab15cf5fd0b16843bd403c7015d68461d05a3c3f515cb1d984a66da.
Traceback (most recent call last):
  File "Scripts/dataserv-client", line 10, in <module>
    cli.main(sys.argv[1:])
  File "c:\Python27\lib\site-packages\dataserv_client\cli.py", line 153, in main
    return getattr(client, command_name)(**arguments)
  File "c:\Python27\lib\site-packages\dataserv_client\api.py", line 174, in build
    rebuild=rebuild)
  File "c:\Python27\lib\site-packages\dataserv_client\builder.py", line 110, in build
    file_hash = self.generate_shard(seed, store_path, cleanup=cleanup)
  File "c:\Python27\lib\site-packages\dataserv_client\builder.py", line 61, in generate_shard
    file_hash = hashlib.sha256(f.read()).hexdigest()
IOError: [Errno 22] Invalid argument

One NAS build is still kicking the above out but ONLY during the multi-machine parallel builds and typically only at the beginning of multi-machine activity.  All drives are WD Green 4TB (4x) spanning. Windows 10 64bit, python 2.7.10, v2.0.3.  after 5-10 minutes the errors stop coming.

**Comment by F483** [comment]
Since this is an OSError, there is not much we can do. Since it is sporadic, retrying the write may be an option.

**Comment by F483** [comment]
Will retry on IOError exactly once, since it is sporadic. https://github.com/Storj/dataserv-client/commit/df760749f7bc5af9a6ed5d3c0a53a2dab9fafc15
