### ISSUE TITLE
2.1.2 fails to find some partition types.

### ISSUE THREAD

**Issue by corv89** [Storj/dataserv-client#116]
2.1.2 fails on ZFS

```
Traceback (most recent call last):
  File "/usr/local/bin/dataserv-client", line 4, in <module>
    __import__('pkg_resources').run_script('dataserv-client==2.1.2', 'dataserv-client')
  File "/usr/local/lib/python3.4/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1652, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.4/site-packages/dataserv_client-2.1.2-py3.4.egg/EGG-INFO/scripts/dataserv-client", line 10, in <module>
    cli.main(sys.argv[1:])
  File "/usr/local/lib/python3.4/site-packages/dataserv_client-2.1.2-py3.4.egg/dataserv_client/cli.py", line 165, in main
    config_path=arguments.pop("config_path"),
  File "/usr/local/lib/python3.4/site-packages/dataserv_client-2.1.2-py3.4.egg/dataserv_client/api.py", line 61, in __init__
    if control.util.get_fs_type(self.store_path) == "vfat":
  File "/usr/local/lib/python3.4/site-packages/dataserv_client-2.1.2-py3.4.egg/dataserv_client/control/util.py", line 51, in get_fs_type
    raise exceptions.PartitionTypeNotFound(path)
dataserv_client.exceptions.PartitionTypeNotFound: Couldn't find partition type for path: '/Z2/storj'!
```

**Comment by F483** [comment]
andrey: hi, got error with latest build

Traceback (most recent call last):
 File "dataserv-client", line 10, in <module>
 File "E:\dataserv-client\dataserv_client\cli.py", line 165, in main
 File "E:\dataserv-client\dataserv_client\api.py", line 61, in __init__
 File "E:\dataserv-client\dataserv_client\control\util.py", line 51, in get_fs_type
dataserv_client.exceptions.PartitionTypeNotFound: Couldn't find partition type for path: 'd:\storj2'!
its win7 soft raid0 dynamic disks

**Comment by F483** [comment]
Fixed in https://github.com/Storj/dataserv-client/commit/6aaea61941107ab63c48d1b8c93da4c168ec2ecf
