### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'decode'

### ISSUE THREAD

**Issue by littleskunk** [Storj/dataserv-client#133]
heunland found a bug in the client recovery

C:\Storj\dataserv-client>dataserv-client --url=http://status.driveshare.org:5000
poll
INFO dataserv_client.api 131: Pinging server 'http://status.driveshare.org:5000'
at 2015-09-12 08:23:36.
INFO dataserv_client.messaging 42: Query: http://status.driveshare.org:5000/api/
address
WARNING dataserv_client.messaging 66: URLError(TimeoutError(10060, 'A connection
attempt failed because the connected party did not properly respond after a per
iod of time, or established connection failed because connected host has failed
to respond', None, 10060, None),)
INFO dataserv_client.messaging 77: Query retry in 30 seconds.
INFO dataserv_client.messaging 42: Query: http://status.driveshare.org:5000/api/
address
Traceback (most recent call last):
 File "dataserv-client", line 10, in <module>
 File "E:\dataserv-client\dataserv_client\cli.py", line 167, in main
 File "E:\dataserv-client\dataserv_client\api.py", line 149, in poll
 File "E:\dataserv-client\dataserv_client\api.py", line 132, in ping
 File "E:\dataserv-client\dataserv_client\messaging.py", line 120, in ping
 File "E:\dataserv-client\dataserv_client\messaging.py", line 39, in _url_query  File "E:\dataserv-client\dataserv_client\messaging.py", line 96, in _create_au
thentication_headers
 File "E:\dataserv-client\dataserv_client\messaging.py", line 84, in _get_serve
r_address
AttributeError: 'NoneType' object has no attribute 'decode'

**Comment by littleskunk** [comment]
Bug confirmed. Stoped my test server and start a client with poll. In the first run i get a other exception but 30 sec retry as well. I started my server so the retry can do his job but in the second run i get the same exception

AttributeError: 'NoneType' object has no attribute 'decode'

**Comment by littleskunk** [comment]
Recovery did not return the response of the call. That was the reason for NoneType. Added the missing return.

Retest ok. Bugfix will be in the next dataserv-lient version (current version 2.1.2)
