### ISSUE TITLE
Failed to load config on CentOS 6.7

### ISSUE THREAD

**Issue by josephting** [Storj/dataserv-client#135]
Trying to upgrade from v1.3.

OS: CentOS 6.7 x64

Command ran
`dataserv-client version`

Returns
```
WARNING dataserv_client.api 66: Couldn't detected partition type for '/root/.sto
rj/store'
Traceback (most recent call last):
  File "/usr/local/bin/dataserv-client", line 10, in <module>
    cli.main(sys.argv[1:])
  File "/usr/local/lib/python3.4/site-packages/dataserv_client/cli.py", line 165
, in main
    config_path=arguments.pop("config_path"),
  File "/usr/local/lib/python3.4/site-packages/dataserv_client/api.py", line 68,
 in __init__
    self.cfg = control.config.get(self.btctxstore, self.cfg_path)
  File "/usr/local/lib/python3.4/site-packages/dataserv_client/control/config.py
", line 59, in get
    cfg = read(path, password=password)
  File "/usr/local/lib/python3.4/site-packages/dataserv_client/control/config.py
", line 10, in read
    return json.loads(config_file.read())
  File "/usr/local/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
```

`df -h`
```
Filesystem      Size  Used Avail Use% Mounted on
/dev/simfs       15G   14G  1.4G  92% /
none            512M  4.0K  512M   1% /dev
none            512M     0  512M   0% /dev/shm
```

**Comment by F483** [comment]
It looks like your config is corrupt. What does your config look like `/root/.storj/config.json`, be sure not to post the wallet.

**Comment by josephting** [comment]
Oh, I tried to make sure if it was the client didn't have permission to create the config.json file when I was still on 2.1.2 so I ran `touch /root/.storj/config.json` earlier.

Removed it now and config.json is supposedly properly formed now but the warning is still there.
I suppose this can be ignored?

```
[root@vps .storj]# dataserv-client version
WARNING dataserv_client.api 66: Couldn't detected partition type for '/root/.sto
rj/store'
2.1.3
```

Sorry about this.

**Comment by littleskunk** [comment]
Please close the bug
