### ISSUE TITLE
Synology Debian client error 2.1.2 and up

### ISSUE THREAD

**Issue by thalantis** [Storj/dataserv-client#140]
Have debian-chroot (8.1.6) package installed on my synology (ds 1815+)

followed the guide here 
http://blog.storj.io/post/127256189103/installing-dataserv-client-on-a-synology-nas-using

step 10 works
pip3 install dataserv-client==1.3.0

when upgrading to 2.1.4 i get the following error

root@nas:/# dataserv-client version
Traceback (most recent call last):
  File "/usr/local/bin/dataserv-client", line 6, in <module>
    from dataserv_client import cli
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/cli.py", line 3, in <module>
    from dataserv_client import api
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/api.py", line 11, in <module>
    from dataserv_client import control
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/control/__init__.py", line 3, in <module>
    from . import util
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/control/util.py", line 1, in <module>
    import psutil
  File "/usr/local/lib/python3.4/dist-packages/psutil/__init__.py", line 63, in <module>
    from . import _pslinux as _psplatform
  File "/usr/local/lib/python3.4/dist-packages/psutil/_pslinux.py", line 153, in <module>
    scputimes = namedtuple('scputimes', _get_cputimes_fields())
  File "/usr/local/lib/python3.4/dist-packages/psutil/_pslinux.py", line 137, in _get_cputimes_fields
    with open('/proc/stat', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/proc/stat'

when i make a fake stat file i get

root@nas:/# dataserv-client version
Traceback (most recent call last):
  File "/usr/local/bin/dataserv-client", line 6, in <module>
    from dataserv_client import cli
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/cli.py", line 3, in <module>
    from dataserv_client import api
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/api.py", line 11, in <module>
    from dataserv_client import control
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/control/__init__.py", line 3, in <module>
    from . import util
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/control/util.py", line 1, in <module>
    import psutil
  File "/usr/local/lib/python3.4/dist-packages/psutil/__init__.py", line 1401, in <module>
    _last_cpu_times = cpu_times()
  File "/usr/local/lib/python3.4/dist-packages/psutil/__init__.py", line 1396, in cpu_times
    return _psplatform.cpu_times()
  File "/usr/local/lib/python3.4/dist-packages/psutil/_pslinux.py", line 239, in cpu_times
    return scputimes(*fields)
TypeError: __new__() missing 6 required positional arguments: 'nice', 'system', 'idle', 'iowait', 'irq', and 'softirq'

when i install 2.0.3 via -> pip3 install dataserv-client==2.0.3 it works
from 2.1.2 and up i get above errors

**Comment by littleskunk** [comment]
Please install python-dev and try again.

**Comment by thalantis** [comment]
gives me this error after installing dataserv-client and doing version

root@Thalantis-nas:/# dataserv-client version
Traceback (most recent call last):
  File "/usr/local/bin/dataserv-client", line 10, in <module>
    cli.main(sys.argv[1:])
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/cli.py", line 188, in main
    config_path=arguments.pop("config_path"),
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/api.py", line 60, in __init__
    fstype = control.util.get_fs_type(self.store_path)
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/control/util.py", line 38, in get_fs_type
    for partition in psutil.disk_partitions():
  File "/usr/local/lib/python3.4/dist-packages/psutil/__init__.py", line 1660, in disk_partitions
    return _psplatform.disk_partitions(all)
  File "/usr/local/lib/python3.4/dist-packages/psutil/_pslinux.py", line 697, in disk_partitions
    partitions = cext.disk_partitions()
FileNotFoundError: [Errno 2] No such file or directory: '/etc/mtab'

**Comment by thalantis** [comment]
but dataserv-client without anything behind it works

**Comment by littleskunk** [comment]
Looks like your linux user has no home directory (default for config). Please try --config_path

**Comment by littleskunk** [comment]
Same exception with --config_path config

@F483 get_fs_type again. Try catch needed?

**Comment by littleskunk** [comment]
same problem with Synology DS 213air

**Comment by littleskunk** [comment]
The problem debian-chroot: https://code.google.com/p/psutil/issues/detail?id=434

**Comment by littleskunk** [comment]
will be fixed in the next version

**Comment by thalantis** [comment]
have installed version 2.1.4 but sill have the same error

**Comment by littleskunk** [comment]
The fix will be in the next version or if you dont want to wait you can install the develop branch from github
