### ISSUE TITLE
Freezed, dead lock?

### ISSUE THREAD

**Issue by alphaonex86** [Storj/dataserv-client#155]
Hello, I have this bug with the version 1.3 AND 2.1.3, mostly when I have problem on my internet during few minutes, the service is blocked AND NEVER RESUME, I need shutdown and restart manually:

INFO dataserv_client.api 135: Pinging server 'http://switch.driveshare.org' at 2015-09-15 20:10:01.
INFO dataserv_client.messaging 43: Query: http://switch.driveshare.org/api/ping/1DRB3yxhjgEQhxAXRUiBysv5Jj4YPHsA8S
INFO dataserv_client.api 135: Pinging server 'http://switch.driveshare.org' at 2015-09-15 20:10:27.
INFO dataserv_client.messaging 43: Query: http://switch.driveshare.org/api/ping/1DRB3yxhjgEQhxAXRUiBysv5Jj4YPHsA8S
WARNING dataserv_client.messaging 67: URLError(gaierror(-3, 'Temporary failure in name resolution'),)
INFO dataserv_client.messaging 78: Query retry in 30 seconds.
INFO dataserv_client.messaging 43: Query: http://switch.driveshare.org/api/ping/1DRB3yxhjgEQhxAXRUiBysv5Jj4YPHsA8S
WARNING dataserv_client.messaging 67: URLError(gaierror(-3, 'Temporary failure in name resolution'),)
INFO dataserv_client.messaging 78: Query retry in 30 seconds.
INFO dataserv_client.messaging 43: Query: http://switch.driveshare.org/api/ping/1DRB3yxhjgEQhxAXRUiBysv5Jj4YPHsA8S
WARNING dataserv_client.messaging 67: URLError(gaierror(-3, 'Temporary failure in name resolution'),)
INFO dataserv_client.messaging 78: Query retry in 30 seconds.
INFO dataserv_client.messaging 43: Query: http://switch.driveshare.org/api/ping/1DRB3yxhjgEQhxAXRUiBysv5Jj4YPHsA8S
^CTraceback (most recent call last):
  File "/usr/lib64/python3.3/urllib/request.py", line 1248, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib64/python3.3/http/client.py", line 1065, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python3.3/http/client.py", line 1103, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python3.3/http/client.py", line 1061, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python3.3/http/client.py", line 906, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.3/http/client.py", line 844, in send
    self.connect()
  File "/usr/lib64/python3.3/http/client.py", line 822, in connect
    self.timeout, self.source_address)
  File "/usr/lib64/python3.3/socket.py", line 417, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.3/site-packages/dataserv_client-2.1.3-py3.3.egg/dataserv_client/messaging.py", line 44, in _url_query
    response = urllib.request.urlopen(req)
  File "/usr/lib64/python3.3/urllib/request.py", line 156, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.3/urllib/request.py", line 469, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.3/urllib/request.py", line 487, in _open
    '_open', req)
  File "/usr/lib64/python3.3/urllib/request.py", line 447, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.3/urllib/request.py", line 1274, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib64/python3.3/urllib/request.py", line 1251, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.3/urllib/request.py", line 1248, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib64/python3.3/http/client.py", line 1065, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python3.3/http/client.py", line 1103, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python3.3/http/client.py", line 1061, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python3.3/http/client.py", line 906, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.3/http/client.py", line 844, in send
    self.connect()
  File "/usr/lib64/python3.3/http/client.py", line 822, in connect
    self.timeout, self.source_address)
  File "/usr/lib64/python3.3/socket.py", line 417, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.3/site-packages/dataserv_client-2.1.3-py3.3.egg/dataserv_client/messaging.py", line 44, in _url_query
    response = urllib.request.urlopen(req)
  File "/usr/lib64/python3.3/urllib/request.py", line 156, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.3/urllib/request.py", line 469, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.3/urllib/request.py", line 487, in _open
    '_open', req)
  File "/usr/lib64/python3.3/urllib/request.py", line 447, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.3/urllib/request.py", line 1274, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib64/python3.3/urllib/request.py", line 1251, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.3/urllib/request.py", line 1248, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib64/python3.3/http/client.py", line 1065, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python3.3/http/client.py", line 1103, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python3.3/http/client.py", line 1061, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python3.3/http/client.py", line 906, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.3/http/client.py", line 844, in send
    self.connect()
  File "/usr/lib64/python3.3/http/client.py", line 822, in connect
    self.timeout, self.source_address)
  File "/usr/lib64/python3.3/socket.py", line 417, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.3/site-packages/dataserv_client-2.1.3-py3.3.egg/dataserv_client/messaging.py", line 44, in _url_query
    response = urllib.request.urlopen(req)
  File "/usr/lib64/python3.3/urllib/request.py", line 156, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.3/urllib/request.py", line 469, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.3/urllib/request.py", line 487, in _open
    '_open', req)
  File "/usr/lib64/python3.3/urllib/request.py", line 447, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.3/urllib/request.py", line 1274, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib64/python3.3/urllib/request.py", line 1251, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dataserv-client", line 10, in <module>
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C  File "/usr/lib64/python3.3/site-packages/dataserv_client-2.1.3-py3.3.egg/dataserv_client/cli.py", line 190, in main
    return getattr(client, command_name)(**arguments)
  File "/usr/lib64/python3.3/site-packages/dataserv_client-2.1.3-py3.3.egg/dataserv_client/api.py", line 224, in farm
    self.poll(delay=delay, limit=limit)
  File "/usr/lib64/python3.3/site-packages/dataserv_client-2.1.3-py3.3.egg/dataserv_client/api.py", line 153, in poll
    self.ping()
  File "/usr/lib64/python3.3/site-packages/dataserv_client-2.1.3-py3.3.egg/dataserv_client/api.py", line 136, in ping
    self.messenger.ping()
  File "/usr/lib64/python3.3/site-packages/dataserv_client-2.1.3-py3.3.egg/dataserv_client/messaging.py", line 113, in ping
    return self._url_query("/api/ping/%s" % self.auth_address())
  File "/usr/lib64/python3.3/site-packages/dataserv_client-2.1.3-py3.3.egg/dataserv_client/messaging.py", line 68, in _url_query
    self._handle_connection_error(api_path, retries, authenticate)
  File "/usr/lib64/python3.3/site-packages/dataserv_client-2.1.3-py3.3.egg/dataserv_client/messaging.py", line 80, in _handle_connection_error
    return self._url_query(api_path, retries + 1, authenticate)
  File "/usr/lib64/python3.3/site-packages/dataserv_client-2.1.3-py3.3.egg/dataserv_client/messaging.py", line 68, in _url_query
    self._handle_connection_error(api_path, retries, authenticate)
  File "/usr/lib64/python3.3/site-packages/dataserv_client-2.1.3-py3.3.egg/dataserv_client/messaging.py", line 80, in _handle_connection_error
    return self._url_query(api_path, retries + 1, authenticate)
  File "/usr/lib64/python3.3/site-packages/dataserv_client-2.1.3-py3.3.egg/dataserv_client/messaging.py", line 68, in _url_query
    self._handle_connection_error(api_path, retries, authenticate)
  File "/usr/lib64/python3.3/site-packages/dataserv_client-2.1.3-py3.3.egg/dataserv_client/messaging.py", line 80, in _handle_connection_error
    return self._url_query(api_path, retries + 1, authenticate)
  File "/usr/lib64/python3.3/site-packages/dataserv_client-2.1.3-py3.3.egg/dataserv_client/messaging.py", line 44, in _url_query
    response = urllib.request.urlopen(req)
  File "/usr/lib64/python3.3/urllib/request.py", line 156, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.3/urllib/request.py", line 469, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.3/urllib/request.py", line 487, in _open
    '_open', req)
  File "/usr/lib64/python3.3/urllib/request.py", line 447, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.3/urllib/request.py", line 1274, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib64/python3.3/urllib/request.py", line 1253, in do_open
    r = h.getresponse()
  File "/usr/lib64/python3.3/http/client.py", line 1147, in getresponse
    response.begin()
  File "/usr/lib64/python3.3/http/client.py", line 358, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.3/http/client.py", line 320, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.3/socket.py", line 297, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt

I need fix to resume normal operation automatically when the internet comeback.
Suggestion: past blocking -> unblocking socket IO opt

Cheers,

**Comment by littleskunk** [comment]
I can't confirm the problem. I tryed the windows 2.1.3 and 2.1.4 client and stoped my internet connection. I get the same message (failure in name resolution) but as soon as the connection is online again it works as expected.

If you get the error again please dont stop the poll comand and check if you can ping the server. That way you should see whats going on.

**Comment by alphaonex86** [comment]
Hello,

During my test the poll was blocked but into another terminal ping work.
I don't know well python (I dev in C/C++/Qt), but the backtrace suggest is blocked into the socket read call, few link:
http://stackoverflow.com/questions/16745409/what-does-pythons-socket-recv-return-for-non-blocking-sockets-if-no-data-is-r
https://github.com/Storj/dataserv-client/search?utf8=%E2%9C%93&q=O_NONBLOCK -> not found

Then:
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect(('127.0.0.1',9999))
fcntl.fcntl(s, fcntl.F_SETFL, os.O_NONBLOCK)
Will improve the performance and fix all the blocking case like my case

**Comment by littleskunk** [comment]
30 sec timeout for urlopen now. Fix will be in the next version. Thank your for reporting the bug.

**Comment by alphaonex86** [comment]
Take care, urlopen mean open time with RTT or download time include, fcntl.fcntl(s, fcntl.F_SETFL, os.O_NONBLOCK) is the best solution for me

**Comment by littleskunk** [comment]
Please open a pull request for it.

**Comment by alphaonex86** [comment]
I'm not able to write code in python, but in real p2p without O_NONBLOCK, this cause free chain and will block all the network, maybe it's possible to freeze the actual status.driveshare.org

**Comment by littleskunk** [comment]
At the moment this is a dataserv-client issue and not a server issue. If it is possible to freeze the server, we cant stop that by changing the client code...
The server is only needed for the test group. Devs are working on a p2p network.

urlopen call without timeout will use a unknown default value. I only changed it into 30 sec. I dont think we will get a server problem cause of that. At least no server problem we already have now.

**Comment by alphaonex86** [comment]
It's problem I was with my own C server/client code, O_NONBLOCK protect againts some DDOS attack on client and server side.
You can propage the issue into the p2p network.

Normal, this is more DDOS oriented attack. You will see only at the first DDOS attack.

**Comment by littleskunk** [comment]
storjnode is working with irc.client and not with urlopen. -> https://github.com/Storj/storjnode/tree/develop

However as far as i found out the same "attack" is possible. I will check that later with some unit tests and if i have success i will open some new issues for storjnode.

The dataserv-client freeze will be fixed in the next version (current: 2.1.4). This bug is closed for now.
