### ISSUE TITLE
1.1.0 client did not restart after scheduled maintenance for upgrade. External drive dismounted

### ISSUE THREAD

**Issue by heunland** [Storj/dataserv-client#16]
Maintenance for upgrade was announced, and clients on v1.1.0 should have automatically restarted dataserv-client polling. I have 3 builds of heights 4000, 8000 and 2800 polling on an external 2 TB HDD (ADATA HD710) attached to a Windows 7 desktop (HP Z620 workstation) Version of client running is 1.1.0.

Polling stopped during the upgrade, and then did not restart automatically as expected. Instead, the machine showed an error window stating: 

"dataserv-client.exe -There is no hard drive.
There is no disk in the drive. Insert a disk in the drive \Device\Harddisk1\DR1."

When checking the list of drives in windows explorer, the external drive I was using in fact did not appear in the list of mounted drives, even though its indicator light was still on so the disk was working. 

The command window of my first build gave the following traceback:

Traceback (most recent call last):
 File "dataserv-client", line 9, in <module>
 File "E:\dataserv-client\dataserv_client\cli.py", line 124, in main
 File "E:\dataserv-client\dataserv_client\api.py", line 114, in poll
 File "E:\dataserv-client\dataserv_client\api.py", line 102, in ping
 File "E:\dataserv-client\dataserv_client\api.py", line 66, in _querry
 File "C:\Python34\lib\urllib\request.py", line 161, in urlopen
 File "C:\Python34\lib\urllib\request.py", line 463, in open
 File "C:\Python34\lib\urllib\request.py", line 481, in _open
 File "C:\Python34\lib\urllib\request.py", line 441, in _call_chain
 File "C:\Python34\lib\urllib\request.py", line 1210, in http_open
 File "C:\Python34\lib\urllib\request.py", line 1185, in do_open
 File "C:\Python34\lib\http\client.py", line 1171, in getresponse
 File "C:\Python34\lib\http\client.py", line 351, in begin
 File "C:\Python34\lib\http\client.py", line 321, in _read_status
http.client.BadStatusLine: ''

This build had gone back to the command prompt awaiting the next command.

The other 2 builds showed this traceback:

Traceback (most recent call last):
 File "dataserv-client", line 9, in <module>
 File "E:\dataserv-client\dataserv_client\cli.py", line 124, in main
 File "E:\dataserv-client\dataserv_client\api.py", line 114, in poll
 File "E:\dataserv-client\dataserv_client\api.py", line 102, in ping
 File "E:\dataserv-client\dataserv_client\api.py", line 66, in _querry

and the cursor just kept blinking but did not go back to command prompt until I forced the process to abort.

I was able to refresh the explorer so that the external drive was remounted, after which I restarted polling on the 3 builds without problem.

Power settings on this machine are so that the harddrives never go to sleep or shut down, nor that the monitor shuts off.

**Comment by F483** [comment]
Fixed https://github.com/Storj/dataserv-client/commit/ad7a390a5e811cd59b930a30d875ad76daeb4b3c
