### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded in comparison

### ISSUE THREAD

**Issue by alphaonex86** [Storj/dataserv-client#160]
Infinity loop:

socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.3/site-packages/dataserv_client-2.1.4-py3.3.egg/dataserv_client/messaging.py", line 45, in _url_query
    response = urllib.request.urlopen(req)
  File "/usr/lib64/python3.3/urllib/request.py", line 156, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.3/urllib/request.py", line 469, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.3/urllib/request.py", line 487, in _open
    '_open', req)
  File "/usr/lib64/python3.3/urllib/request.py", line 447, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.3/urllib/request.py", line 1274, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib64/python3.3/urllib/request.py", line 1251, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dataserv-client", line 10, in <module>
    cli.main(sys.argv[1:])
  File "/usr/lib64/python3.3/site-packages/dataserv_client-2.1.4-py3.3.egg/dataserv_client/cli.py", line 190, in main
    return getattr(client, command_name)(**arguments)
  File "/usr/lib64/python3.3/site-packages/dataserv_client-2.1.4-py3.3.egg/dataserv_client/api.py", line 235, in farm
    self.poll(delay=delay, limit=limit)
  File "/usr/lib64/python3.3/site-packages/dataserv_client-2.1.4-py3.3.egg/dataserv_client/api.py", line 161, in poll
    self.ping()
  File "/usr/lib64/python3.3/site-packages/dataserv_client-2.1.4-py3.3.egg/dataserv_client/api.py", line 144, in ping
    self.messenger.ping()
  File "/usr/lib64/python3.3/site-packages/dataserv_client-2.1.4-py3.3.egg/dataserv_client/messaging.py", line 109, in ping
    return self._url_query("/api/ping/%s" % self.auth_address())
  File "/usr/lib64/python3.3/site-packages/dataserv_client-2.1.4-py3.3.egg/dataserv_client/messaging.py", line 69, in _url_query
    return self._handle_connection_error(api_path, retries, authenticate)
  File "/usr/lib64/python3.3/site-packages/dataserv_client-2.1.4-py3.3.egg/dataserv_client/messaging.py", line 81, in _handle_connection_error
.............
  File "/usr/lib64/python3.3/site-packages/dataserv_client-2.1.4-py3.3.egg/dataserv_client/messaging.py", line 81, in _handle_connection_error
    return self._url_query(api_path, retries + 1, authenticate)
  File "/usr/lib64/python3.3/site-packages/dataserv_client-2.1.4-py3.3.egg/dataserv_client/messaging.py", line 69, in _url_query
    return self._handle_connection_error(api_path, retries, authenticate)
  File "/usr/lib64/python3.3/site-packages/dataserv_client-2.1.4-py3.3.egg/dataserv_client/messaging.py", line 81, in _handle_connection_error
    return self._url_query(api_path, retries + 1, authenticate)
  File "/usr/lib64/python3.3/site-packages/dataserv_client-2.1.4-py3.3.egg/dataserv_client/messaging.py", line 40, in _url_query
    self.btctxstore, self._get_server_address(), self.wif
  File "/usr/lib64/python3.3/site-packages/storjcore-0.0.3-py3.3.egg/storjcore/auth.py", line 38, in create_headers
    signature = btctxstore.sign_unicode(sender_wif, msg)
  File "/usr/lib64/python3.3/site-packages/btctxstore-4.5.0-py3.3.egg/btctxstore/api.py", line 191, in sign_unicode
    return self.sign_data(wif, hexdata)
  File "/usr/lib64/python3.3/site-packages/btctxstore-4.5.0-py3.3.egg/btctxstore/api.py", line 174, in sign_data
    sigdata = control.sign_data(self.testnet, data, key)
  File "/usr/lib64/python3.3/site-packages/btctxstore-4.5.0-py3.3.egg/btctxstore/control.py", line 293, in sign_data
    pk = ecdsa.SigningKey.from_secret_exponent(secretexponent, curve=SECP256k1)
  File "/usr/lib64/python3.3/site-packages/ecdsa-0.13-py3.3.egg/ecdsa/keys.py", line 142, in from_secret_exponent
  File "/usr/lib64/python3.3/site-packages/ecdsa-0.13-py3.3.egg/ecdsa/keys.py", line 28, in from_public_point
  File "/usr/lib64/python3.3/site-packages/ecdsa-0.13-py3.3.egg/ecdsa/ecdsa.py", line 87, in __init__
  File "/usr/lib64/python3.3/site-packages/ecdsa-0.13-py3.3.egg/ecdsa/ellipticcurve.py", line 143, in __rmul__
  File "/usr/lib64/python3.3/site-packages/ecdsa-0.13-py3.3.egg/ecdsa/ellipticcurve.py", line 134, in __mul__
  File "/usr/lib64/python3.3/site-packages/ecdsa-0.13-py3.3.egg/ecdsa/ellipticcurve.py", line 107, in __add__
  File "/usr/lib64/python3.3/site-packages/ecdsa-0.13-py3.3.egg/ecdsa/ellipticcurve.py", line 73, in __init__
  File "/usr/lib64/python3.3/site-packages/ecdsa-0.13-py3.3.egg/ecdsa/ellipticcurve.py", line 59, in contains_point
RuntimeError: maximum recursion depth exceeded in comparison

**Comment by littleskunk** [comment]
Looks like the farm command? https://github.com/Storj/dataserv-client/blob/develop/dataserv_client/api.py#L241

I will fix it tomorrow.

**Comment by littleskunk** [comment]
python max recursion is ~1000. For every 30 sec retry 2 recursions calls are needed. Max retry limit will be somewhere between 450 and 500. -> ~4h retry

I will increase the retry delay for farm to 60 sec and the retry limit to 450-500. That way max retry will be ~8h without exception.

**Comment by alphaonex86** [comment]
Can you just drop recursion and use normal loop please?

**Comment by littleskunk** [comment]
I did some unit tests and python recursion is realy a bad. Looks like your idea with the loop is the only solution.

**Comment by littleskunk** [comment]
will be fixed in the next version (after pull request merge)

**Comment by littleskunk** [comment]
Pull request merged. Unit test with 2000 retries passed.
