### ISSUE TITLE
Missing dependencies after install

### ISSUE THREAD

**Issue by gordonwritescode** [Storj/dataserv-client#177]
Working on driveshare-gui (on debian gnu/linux), changed the setup script to use `python` and `pip` instead of `python3` and pip3` - which resolves the unmet dependency issue for the storjnode package (reported earlier).

However, the installed `dataserv-client` package fails to run, missing the `twisted` package.

```
╭─gordon@gordonhall  ~/Code/driveshare-gui  ‹master*› 
╰─$ sudo pip install dataserv-client 
Downloading/unpacking dataserv-client
  Downloading dataserv_client-2.1.12-py2-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): btctxstore>=4.6.0 in /usr/local/lib/python2.7/dist-packages (from dataserv-client)
Requirement already satisfied (use --upgrade to upgrade): partialhash>=1.1.0 in /usr/local/lib/python2.7/dist-packages (from dataserv-client)
Requirement already satisfied (use --upgrade to upgrade): storjcore>=0.0.6 in /usr/local/lib/python2.7/dist-packages (from dataserv-client)
Requirement already satisfied (use --upgrade to upgrade): future>=0.15.0 in /usr/local/lib/python2.7/dist-packages (from dataserv-client)
Requirement already satisfied (use --upgrade to upgrade): RandomIO>=0.2.1 in /usr/local/lib/python2.7/dist-packages (from dataserv-client)
Requirement already satisfied (use --upgrade to upgrade): storjnode>=0.0.18 in /usr/local/lib/python2.7/dist-packages (from dataserv-client)
Requirement already satisfied (use --upgrade to upgrade): psutil>=3.2.2 in /usr/local/lib/python2.7/dist-packages (from dataserv-client)
Requirement already satisfied (use --upgrade to upgrade): pycoin==0.52 in /usr/local/lib/python2.7/dist-packages (from btctxstore>=4.6.0->dataserv-client)
Requirement already satisfied (use --upgrade to upgrade): six==1.9.0 in /usr/lib/python2.7/dist-packages (from btctxstore>=4.6.0->dataserv-client)
Requirement already satisfied (use --upgrade to upgrade): ecdsa==0.13 in /usr/local/lib/python2.7/dist-packages (from btctxstore>=4.6.0->dataserv-client)
Requirement already satisfied (use --upgrade to upgrade): pycrypto>=2.6.1 in /usr/local/lib/python2.7/dist-packages (from RandomIO>=0.2.1->dataserv-client)
Installing collected packages: dataserv-client
Successfully installed dataserv-client
Cleaning up...
╭─gordon@gordonhall  ~/Code/driveshare-gui  ‹master*› 
╰─$ dataserv-client
Traceback (most recent call last):
  File "/usr/local/bin/dataserv-client", line 6, in <module>
    from dataserv_client import cli
  File "/usr/local/lib/python2.7/dist-packages/dataserv_client/cli.py", line 4, in <module>
    from dataserv_client import api
  File "/usr/local/lib/python2.7/dist-packages/dataserv_client/api.py", line 7, in <module>
    import storjnode
  File "/usr/local/lib/python2.7/dist-packages/storjnode/__init__.py", line 1, in <module>
    from .log import logging  # NOQA auto init logging for `import storjnode`
  File "/usr/local/lib/python2.7/dist-packages/storjnode/log.py", line 4, in <module>
    from twisted.python import log as _log
ImportError: No module named twisted.python

```

**Comment by littleskunk** [comment]
Impossible to solve remote. I will look into it as soon as i am at home.

**Comment by gordonwritescode** [comment]
Looks like several packages are missing from the requirements.txt - i made it through by manually installing each missing dep, but then ran into an issue where the debian repo's pip package relies on an older version of requests - thus breaking my pip. ._.

Installing pip outside of apt and trying again. Will add missing deps to requirements.txt after i'm clear.

**Comment by littleskunk** [comment]
That is impossible. Travis unit test would fail as soon as a requirement is missing. I dont think the problem is that easy.

**Comment by gordonwritescode** [comment]
Apologies for the "stream of consciousness" debugging. After killing APT's version of `pip` and installing with `easy_install` (which has the newer version of pip that does not rely on the outdated requests package), all the deps install correctly - except for graphviz which gives:

```
╭─gordon@gordonhall  ~/Code/driveshare-gui  ‹master*› 
╰─$ dataserv-client version
Traceback (most recent call last):
  File "/usr/local/bin/dataserv-client", line 6, in <module>
    from dataserv_client import cli
  File "/usr/local/lib/python2.7/dist-packages/dataserv_client/cli.py", line 4, in <module>
    from dataserv_client import api
  File "/usr/local/lib/python2.7/dist-packages/dataserv_client/api.py", line 7, in <module>
    import storjnode
  File "/usr/local/lib/python2.7/dist-packages/storjnode/__init__.py", line 3, in <module>
    from . import network  # NOQA
  File "/usr/local/lib/python2.7/dist-packages/storjnode/network/__init__.py", line 7, in <module>
    from . import map  # NOQA
  File "/usr/local/lib/python2.7/dist-packages/storjnode/network/map.py", line 6, in <module>
    import pygraphviz
  File "/usr/local/lib/python2.7/dist-packages/pygraphviz/__init__.py", line 58, in <module>
    from .agraph import AGraph, Node, Edge, Attribute, ItemAttribute, DotError
  File "/usr/local/lib/python2.7/dist-packages/pygraphviz/agraph.py", line 26, in <module>
    from . import graphviz as gv
  File "/usr/local/lib/python2.7/dist-packages/pygraphviz/graphviz.py", line 28, in <module>
    _graphviz = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/pygraphviz/graphviz.py", line 24, in swig_import_helper
    _mod = imp.load_module('_graphviz', fp, pathname, description)
ImportError: /usr/local/lib/python2.7/dist-packages/pygraphviz/_graphviz.so: undefined symbol: Agundirected
```

Any ideas here? I installed according the the Debian instruction in the README.

**Comment by gordonwritescode** [comment]
Okay, i was able to resolve this dependency nightmare using the info here: https://github.com/pygraphviz/pygraphviz/issues/71

**Comment by littleskunk** [comment]
Looks like you installed everything correct but i have to ask it to be sure. Did you install pygraphviz yourself with install-option or did you install it as dependency (pip install dataserv-client or pip install -re requirements.txt)?

**Comment by gordonwritescode** [comment]
Installed with --install-option

**Comment by littleskunk** [comment]
Did you use the path mentioned in the README? Please check that both path exists on your system.
