### ISSUE TITLE
dataserv-client 2.1.12 crashes on OSX

### ISSUE THREAD

**Issue by lunokhod** [Storj/dataserv-client#192]
I decided to upgrade from dataserv-client 2.1.4 to the latest release (2.1.12). Though everything with 2.1.4 worked fine, 2.1.12 crashes immediately, even when checking the version.

I am running OSX 10.11.2, and have tried to uninstall/install/upgrade, all with the same result.

~~~~
% dataserv-client version
Traceback (most recent call last):
  File "/usr/local/bin/dataserv-client", line 6, in <module>
    from dataserv_client import cli
  File "/usr/local/lib/python2.7/site-packages/dataserv_client/cli.py", line 4, in <module>
    from dataserv_client import api
  File "/usr/local/lib/python2.7/site-packages/dataserv_client/api.py", line 7, in <module>
    import storjnode
  File "/usr/local/lib/python2.7/site-packages/storjnode/__init__.py", line 3, in <module>
    from . import network  # NOQA
  File "/usr/local/lib/python2.7/site-packages/storjnode/network/__init__.py", line 1, in <module>
    from . import node  # NOQA
  File "/usr/local/lib/python2.7/site-packages/storjnode/network/node.py", line 13, in <module>
    from pyp2p.unl import UNL
  File "/usr/local/lib/python2.7/site-packages/pyp2p/unl.py", line 6, in <module>
    from .lib import *  # FIXME * is evil!
  File "/usr/local/lib/python2.7/site-packages/pyp2p/lib.py", line 37, in <module>
    ip = IPDB()
  File "/usr/local/lib/python2.7/site-packages/pyroute2/__init__.py", line 89, in __new__
    cls.register(cls.registry['class'])
  File "/usr/local/lib/python2.7/site-packages/pyroute2/__init__.py", line 69, in __getitem__
    [name], 0)
  File "/usr/local/lib/python2.7/site-packages/pyroute2/ipdb/__init__.py", line 396, in <module>
    from pyroute2.iproute import IPRoute
  File "/usr/local/lib/python2.7/site-packages/pyroute2/iproute.py", line 109, in <module>
    from pyroute2.netlink.rtnl.tcmsg import get_htb_parameters
  File "/usr/local/lib/python2.7/site-packages/pyroute2/netlink/rtnl/tcmsg.py", line 29, in <module>
    _psched = open('/proc/net/psched', 'r')
IOError: [Errno 2] No such file or directory: '/proc/net/psched'
~~~~

**Comment by littleskunk** [comment]
Same problem if you use the osx binary?
https://github.com/Storj/dataserv-client/releases/download/v2.1.12/dataserv-client-2.1.12.osx64.zip

**Comment by lunokhod** [comment]
The binary appears to work, but I would much prefer building from source.

**Comment by littleskunk** [comment]
pyp2p version 0.5.8 should work. 
```
pip install pyp2p==0.5.8
```

Moved the issue to pyp2p: https://github.com/Storj/pyp2p/issues/16

Thank you for reporting the bug.

**Comment by lunokhod** [comment]
I installed the old version of pyp2p (0.5.8), but this just gives a different problem. Here is the output I get from checking the version

~~~~
d% dataserv-client version
Traceback (most recent call last):
  File "/usr/local/bin/dataserv-client", line 10, in <module>
    cli.main(sys.argv[1:])
  File "/usr/local/lib/python2.7/site-packages/dataserv_client/cli.py", line 188, in main
    config_path=arguments.pop("config_path"),
  File "/usr/local/lib/python2.7/site-packages/dataserv_client/api.py", line 68, in __init__
    self.cfg = control.config.get(self.btctxstore, self.cfg_path)
  File "/usr/local/lib/python2.7/site-packages/dataserv_client/control/config.py", line 60, in get
    cfg = migrate(btctxstore, path, cfg, password=password)
  File "/usr/local/lib/python2.7/site-packages/dataserv_client/control/config.py", line 103, in migrate
    cfg = _MIGRATIONS[cfg['version']](btctxstore, cfg)
KeyError: u'3.0.0'
~~~~
