### ISSUE TITLE
Failed to install on CentOS 6.7

### ISSUE THREAD

**Issue by josephting** [Storj/dataserv-client#194]
Specifically, there's a problem with getting RandomIO installed.
Here's some logs that might help.

```
Collecting RandomIO>=0.2.1 (from dataserv-client)
  Getting page https://pypi.python.org/simple/randomio/
  1 location(s) to search for versions of RandomIO:
  * https://pypi.python.org/simple/randomio/
  Getting page https://pypi.python.org/simple/randomio/
  Analyzing links from page https://pypi.python.org/simple/randomio/
    Found link https://pypi.python.org/packages/source/R/RandomIO/RandomIO-0.2.0.tar.gz#md5=033babdbdec4849dbcd0b21a0d830b90 (from https://pypi.python.org/simple/randomio/), version: 0.2.0
    Found link https://pypi.python.org/packages/source/R/RandomIO/RandomIO-0.2.1.tar.gz#md5=ad82eae3e107b467f6b7be9bf7f91db5 (from https://pypi.python.org/simple/randomio/), version: 0.2.1
  Using cached RandomIO-0.2.1.tar.gz
  Downloading from URL https://pypi.python.org/packages/source/R/RandomIO/RandomIO-0.2.1.tar.gz#md5=ad82eae3e107b467f6b7be9bf7f91db5 (from https://pypi.python.org/simple/randomio/)
  Running setup.py (path:/tmp/pip-build-ocqseA/RandomIO/setup.py) egg_info for package RandomIO
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-ocqseA/RandomIO/setup.py", line 71, in <module>
        __version__),
    ValueError: zero length field name in format
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-ocqseA/RandomIO/setup.py", line 71, in <module>
        __version__),
    ValueError: zero length field name in format
```
[Link to code](https://github.com/Storj/RandomIO/blob/v0.2.1/setup.py#L71)

```
[root@vps3 ~]# uname -r
2.6.32-573.el6.x86_64
[root@vps3 ~]# cat /etc/redhat-release
CentOS release 6.7 (Final)
[root@vps3 ~]# python --version
Python 2.6.6
[root@vps3 ~]# pip --version
pip 7.1.2 from /usr/lib/python2.6/site-packages (python 2.6)
```

**Comment by josephting** [comment]
Seems like I only needed Python 2.7 for it to work properly.
Including the minimum python version requirement in the docs can avoid this confusion.
