### ISSUE TITLE
IOError when running dataserv-client in Debian Chroot on Synology NAS

### ISSUE THREAD

**Issue by CurreE** [Storj/dataserv-client#201]
I've been trying to figure out how to run dataserv-client on my Synology DS416 NAS.  I got dataserv-client installed using pip, but when I run it I get this error at start up:

root@ErikDS416:/# dataserv-client version
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/psutil/_pslinux.py", line 202, in <module>
    scputimes = set_scputimes_ntuple("/proc")
  File "/usr/local/lib/python2.7/dist-packages/psutil/_common.py", line 112, in wrapper
    ret = cache[key] = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/psutil/_pslinux.py", line 184, in set_scputimes_ntuple
    with open_binary('%s/stat' % procfs_path) as f:
  File "/usr/local/lib/python2.7/dist-packages/psutil/_pslinux.py", line 138, in open_binary
    return open(fname, "rb", **kwargs)
IOError: [Errno 2] No such file or directory: '/proc/stat'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/psutil/__init__.py", line 1435, in <module>
    _last_cpu_times = cpu_times()
  File "/usr/local/lib/python2.7/dist-packages/psutil/__init__.py", line 1429, in cpu_times
    return _psplatform.cpu_times()
  File "/usr/local/lib/python2.7/dist-packages/psutil/_pslinux.py", line 301, in cpu_times
    set_scputimes_ntuple(procfs_path)
  File "/usr/local/lib/python2.7/dist-packages/psutil/_common.py", line 112, in wrapper
    ret = cache[key] = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/psutil/_pslinux.py", line 184, in set_scputimes_ntuple
    with open_binary('%s/stat' % procfs_path) as f:
  File "/usr/local/lib/python2.7/dist-packages/psutil/_pslinux.py", line 138, in open_binary
    return open(fname, "rb", **kwargs)
IOError: [Errno 2] No such file or directory: '/proc/stat'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/psutil/__init__.py", line 1442, in <module>
    _last_per_cpu_times = cpu_times(percpu=True)
  File "/usr/local/lib/python2.7/dist-packages/psutil/__init__.py", line 1431, in cpu_times
    return _psplatform.per_cpu_times()
  File "/usr/local/lib/python2.7/dist-packages/psutil/_pslinux.py", line 314, in per_cpu_times
    set_scputimes_ntuple(procfs_path)
  File "/usr/local/lib/python2.7/dist-packages/psutil/_common.py", line 112, in wrapper
    ret = cache[key] = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/psutil/_pslinux.py", line 184, in set_scputimes_ntuple
    with open_binary('%s/stat' % procfs_path) as f:
  File "/usr/local/lib/python2.7/dist-packages/psutil/_pslinux.py", line 138, in open_binary
    return open(fname, "rb", **kwargs)
IOError: [Errno 2] No such file or directory: '/proc/stat'
2016-01-29 21:48:22,978 WARNING dataserv_client.api 73: [Errno 2] No such file or directory: '/proc/filesystems'
2016-01-29 21:48:22,978 WARNING dataserv_client.api 81: Couldn't detected partition type for '/root/.storj/store'
2.1.12

The error doesn't seem to crash the program, as it continues to execute and show the output of the command I issued (in this case the version command).

**Comment by littleskunk** [comment]
Duplicate https://github.com/Storj/dataserv-client/issues/140
