### ISSUE TITLE
Can't run on Ubuntu 15.10

### ISSUE THREAD

**Issue by VitorVRS** [Storj/dataserv-client#203]
I installed dataserv-client via command-line and when i run

`$ dataserv-client`

i get this message

`Traceback (most recent call last):
  File "/usr/local/bin/dataserv-client", line 6, in <module>
    from dataserv_client import cli
  File "/usr/local/lib/python2.7/dist-packages/dataserv_client/cli.py", line 4, in <module>
    from dataserv_client import api
  File "/usr/local/lib/python2.7/dist-packages/dataserv_client/api.py", line 7, in <module>
    import storjnode
  File "/usr/local/lib/python2.7/dist-packages/storjnode/__init__.py", line 3, in <module>
    from . import network  # NOQA
  File "/usr/local/lib/python2.7/dist-packages/storjnode/network/__init__.py", line 1, in <module>
    from . import node  # NOQA
  File "/usr/local/lib/python2.7/dist-packages/storjnode/network/node.py", line 19, in <module>
    from storjnode.network.file_transfer import FileTransfer
  File "/usr/local/lib/python2.7/dist-packages/storjnode/network/file_transfer.py", line 4, in <module>
    import pyp2p.dht_msg
  File "/usr/local/lib/python2.7/dist-packages/pyp2p/dht_msg.py", line 10, in <module>
    from storjkademlia.node import Node as KadNode
ImportError: No module named storjkademlia.node
`

This error occurs on GUI too when i click on button "START"

Tks

**Comment by littleskunk** [comment]
https://github.com/Storj/driveshare-gui/issues/182
