### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by enkumber** [Storj/dataserv-client#21]
Error during install:

sudo pip3 install dataserv-client
Downloading/unpacking dataserv-client
  Downloading dataserv-client-1.2.1.tar.gz
  Running setup.py (path:/tmp/pip_build_root/dataserv-client/setup.py) egg_info for package dataserv-client
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/dataserv-client/setup.py", line 4, in <module>
        from esky.bdist_esky import Executable
    ImportError: No module named 'esky'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

UBUNTU 14.10

**Comment by super3** [comment]
Sorry you pulled a development version. Use:

    pip install dataserv-client==1.1.0
