### ISSUE TITLE
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by heunland** [Storj/dataserv-client#26]
My client on my laptop build stopped polling with the following traceback:

Traceback (most recent call last):
 File "dataserv-client", line 9, in <module>
 File "E:\dataserv-client\dataserv_client\cli.py", line 124, in main
 File "E:\dataserv-client\dataserv_client\api.py", line 114, in poll
 File "E:\dataserv-client\dataserv_client\api.py", line 102, in ping
 File "E:\dataserv-client\dataserv_client\api.py", line 66, in _querry
 File "C:\Python34\lib\urllib\request.py", line 161, in urlopen
 File "C:\Python34\lib\urllib\request.py", line 463, in open
 File "C:\Python34\lib\urllib\request.py", line 481, in _open
 File "C:\Python34\lib\urllib\request.py", line 441, in _call_chain
 File "C:\Python34\lib\urllib\request.py", line 1210, in http_open
 File "C:\Python34\lib\urllib\request.py", line 1185, in do_open
 File "C:\Python34\lib\http\client.py", line 1171, in getresponse
 File "C:\Python34\lib\http\client.py", line 351, in begin
 File "C:\Python34\lib\http\client.py", line 313, in _read_status
 File "C:\Python34\lib\socket.py", line 374, in readinto
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

so remote host disconnected my client apparently and returned me to the command prompt. I was able to restart polling manually with no further incidents. Could not identify the reason for the remote disconnect.

**Comment by F483** [comment]
See https://github.com/Storj/dataserv-client/issues/38
