### ISSUE TITLE
Ubuntu installation failed

### ISSUE THREAD

**Issue by chrisvdb** [Storj/dataserv-client#27]
The setup instructions for Ubuntu yielded the following error:

```
$ sudo pip3 install dataserv-client
Downloading/unpacking dataserv-client
  Downloading dataserv-client-1.2.1.tar.gz
  Running setup.py (path:/tmp/pip-build-2p4_wfs8/dataserv-client/setup.py) egg_info for package dataserv-client
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-2p4_wfs8/dataserv-client/setup.py", line 4, in <module>
        from esky.bdist_esky import Executable
    ImportError: No module named 'esky'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-2p4_wfs8/dataserv-client/setup.py", line 4, in <module>

    from esky.bdist_esky import Executable

ImportError: No module named 'esky'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-2p4_wfs8/dataserv-client
Storing debug log for failure in /home/chrisvdb/.pip/pip.log
```

**Comment by super3** [comment]
Sorry you pulled a development version. Use:

    pip install dataserv-client==1.1.0
