### ISSUE TITLE
http.client.BadStatusLine

### ISSUE THREAD

**Issue by F483** [Storj/dataserv-client#32]
jawed 8:04 AM Had an exception last night with 1.3.0:
Traceback (most recent call last):
 File "dataserv-client", line 24, in <module>
 File "E:\dataserv-client\dataserv_client\cli.py", line 128, in main
 File "E:\dataserv-client\dataserv_client\api.py", line 116, in poll
 File "E:\dataserv-client\dataserv_client\api.py", line 104, in ping
 File "E:\dataserv-client\dataserv_client\api.py", line 68, in _url_query
 File "C:\Python34\lib\urllib\request.py", line 161, in urlopen
 File "C:\Python34\lib\urllib\request.py", line 463, in open
 File "C:\Python34\lib\urllib\request.py", line 481, in _open
 File "C:\Python34\lib\urllib\request.py", line 441, in _call_chain
 File "C:\Python34\lib\urllib\request.py", line 1210, in http_open
 File "C:\Python34\lib\urllib\request.py", line 1185, in do_open
 File "C:\Python34\lib\http\client.py", line 1171, in getresponse
 File "C:\Python34\lib\http\client.py", line 351, in begin
 File "C:\Python34\lib\http\client.py", line 321, in _read_status
http.client.BadStatusLine: ''
Windows client

**Comment by F483** [comment]
Very likely a duplicate of this issue. https://github.com/Storj/dataserv-client/issues/16

**Comment by F483** [comment]
Fixed https://github.com/Storj/dataserv-client/commit/ad7a390a5e811cd59b930a30d875ad76daeb4b3c
