### ISSUE TITLE
Error handling not ideal: ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by unsystemizer** [Storj/dataserv-client#38]
Could be better handled. Was building a ton of shards, have to revalidate 10k+ shards now.
```
Query url: http://104.236.104.117/api/height/<address>/12690
Traceback (most recent call last):
  File "/usr/local/bin/dataserv-client", line 24, in <module>
    cli.main(sys.argv[1:])
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/cli.py", line 128, in main
    return getattr(client, command_name)(**arguments)
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/api.py", line 130, in build
    cleanup=cleanup, rebuild=rebuild)
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/builder.py", line 64, in build
    self.on_generate_shard(shard_num + 1, seed, file_hash)
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/api.py", line 126, in on_generate_shard
    self._url_query('/api/height/{0}/{1}'.format(self.address, height))
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/api.py", line 68, in _url_query
    response = urllib.request.urlopen(self.url + api_call)
  File "/usr/lib/python3.4/urllib/request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 455, in open
    response = self._open(req, data)
  File "/usr/lib/python3.4/urllib/request.py", line 473, in _open
    '_open', req)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 1202, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.4/urllib/request.py", line 1177, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1172, in getresponse
    response.begin()
  File "/usr/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.4/socket.py", line 371, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
$ dataserv-client version
1.3.0
```

**Comment by F483** [comment]
I though we had all possible connection errors, guess not. This should fixed now and corrected in the next version. 

See https://github.com/Storj/dataserv-client/commit/8c4cfdf2afad7ef60af307af3d19ca43f823ba15
