### ISSUE TITLE
Client doesn't complete expanded build with over 11TB max size

### ISSUE THREAD

**Issue by nameone** [Storj/dataserv-client#44]
On Windows 10. I had a 11TB build which I tried to expand using first: 

dataserv-client.exe --address <BITCOIN_ADDRESS> build --rebuild

That failed because of a server issue which wasn't responding a couple of days ago. So then I tried this instead: 

dataserv-client.exe --store_path <PATH_TO_FOLDER> --max_size <MAX_DATA_SIZE_IN_BYTES> --address <BITCOIN_ADDRESS> build

This failed again when it reached about 67K Height. Below is the traceback from the app.

Traceback (most recent call last):
  File "dataserv-client", line 24, in <module>
  File "E:\dataserv-client\dataserv_client\cli.py", line 128, in main
  File "E:\dataserv-client\dataserv_client\api.py", line 130, in build
  File "E:\dataserv-client\dataserv_client\builder.py", line 64, in build
  File "E:\dataserv-client\dataserv_client\api.py", line 126, in on_generate_shard
  File "E:\dataserv-client\dataserv_client\api.py", line 68, in _url_query
  File "C:\Python34\lib\urllib\request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 463, in open
    response = self._open(req, data)
  File "C:\Python34\lib\urllib\request.py", line 481, in _open
    '_open', req)
  File "C:\Python34\lib\urllib\request.py", line 441, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 1210, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Python34\lib\urllib\request.py", line 1185, in do_open
    r = h.getresponse()
  File "C:\Python34\lib\http\client.py", line 1171, in getresponse
    response.begin()
  File "C:\Python34\lib\http\client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "C:\Python34\lib\http\client.py", line 321, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: ''

Expanding should be easier and faster in my opinion, if we need to scale to 1PB we need to make sure that users can Build and Expand faster than it is currently possible. I have been trying for 3 days to add more storage to my build unsuccessfully. The amount of time it takes to check existing shards is also too long, we should skip that process and get the client to only create new shards for the required expanded storage. Also having to fall back to 0 Height when expanding or rebuilding doesn't sound right as usually I'll be still polling when doing that, so starting from the current build size would be ideal then see the increases as the expansion progresses.

**Comment by F483** [comment]
The BadStatusLine bug has already been fixed and will be rolled out in the next version.
