### ISSUE TITLE
OSX crash during hot fix (aug 21)

### ISSUE THREAD

**Issue by lunokhod** [Storj/dataserv-client#50]
During the hot fix that was applied on August 21, my client on osx crashed. Here is the output.

*For info, I'm running 1.3.0, python 3.4.3, osx 10.10.5*
~~~~
Traceback (most recent call last):
 File "/usr/local/bin/dataserv-client", line 24, in <module>
   cli.main(sys.argv[1:])
 File "/usr/local/lib/python3.4/site-packages/dataserv_client/cli.py", line 128, in main
   return getattr(client, command_name)(**arguments)
 File "/usr/local/lib/python3.4/site-packages/dataserv_client/api.py", line 116, in poll
   self.ping()
 File "/usr/local/lib/python3.4/site-packages/dataserv_client/api.py", line 104, in ping
   return self._url_query("/api/ping/{0}".format(self.address))
 File "/usr/local/lib/python3.4/site-packages/dataserv_client/api.py", line 68, in _url_query
   response = urllib.request.urlopen(self.url + api_call)
 File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 161, in urlopen
   return opener.open(url, data, timeout)
 File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 463, in open
   response = self._open(req, data)
 File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 481, in _open
   '_open', req)
 File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 441, in _call_chain
   result = func(*args)
 File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 1210, in http_open
   return self.do_open(http.client.HTTPConnection, req)
 File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 1185, in do_open
   r = h.getresponse()
 File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 1171, in getresponse
   response.begin()
 File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 351, in begin
   version, status, reason = self._read_status()
 File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 313, in _read_status
   line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
 File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/socket.py", line 374, in readinto
   return self._sock.recv_into(b)
ConnectionResetError: [Errno 54] Connection reset by peer
~~~~

**Comment by F483** [comment]
Connection reset error already fixed and will be rolled out in the next release.

See https://github.com/Storj/dataserv-client/issues/38
