### ISSUE TITLE
Used By Another Process Error

### ISSUE THREAD

**Issue by super3** [Storj/dataserv-client#54]
When running testing on Windows:
```
Resuming from height 1
Error
Traceback (most recent call last):
  File "C:\Users\super3\Code\dataserv-client\tests\test_builder.py", line 60, in test_builder_build
    bucket.build(self.store_path, cleanup=True)
  File "C:\Users\super3\Code\dataserv-client\dataserv_client\builder.py", line 89, in build
    rebuild=rebuild)
  File "C:\Users\super3\Code\dataserv-client\dataserv_client\builder.py", line 62, in generate_shard
    os.remove(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\super3\\AppData\\Local\\Temp\\tmpp11mbzg0\\7460b234c7de598b1e98224b7a3afb48d00c82f6bc5c0c8e0cc52efa9dd1dc64'
```

**Comment by F483** [comment]
Fixed https://github.com/Storj/dataserv-client/commit/5930b8a9bcd08a9a41348292416af0a9a75ba9dc
