### ISSUE TITLE
clients stops working

### ISSUE THREAD

**Issue by beulemann** [Storj/dataserv-client#69]
from time to time my client stops working.

he shows the following error:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/api.py", line 68,                                            in _url_query
    response = urllib.request.urlopen(self.url + api_call)
  File "/usr/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 469, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 507, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 587, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: INTERNAL SERVER ERROR

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/dataserv-client", line 24, in <module>
    cli.main(sys.argv[1:])
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/cli.py", line 128                                           , in main
    return getattr(client, command_name)(**arguments)
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/api.py", line 116                                           , in poll
    self.ping()
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/api.py", line 104                                           , in ping
    return self._url_query("/api/ping/{0}".format(self.address))
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/api.py", line 82,                                            in _url_query
    raise exceptions.FarmerError(self.url)  # pragma: no cover
dataserv_client.exceptions.FarmerError: Farmer error at http://104.236.104.117!

**Comment by F483** [comment]
This looks like an error server side, and was handled correctly by the client.

Thanks for reporting it! We will check the logs and see what the problem is/was.

**Comment by beulemann** [comment]
It happened again. Is it possible to add a function to automatic restart the client?
