### ISSUE TITLE
Crash/Bug

### ISSUE THREAD

**Issue by starsoccer** [Storj/dataserv-client#7]
Traceback (most recent call last):
  File "C:\Python34\lib\urllib\request.py", line 1182, in do_open
    tunnel_headers[proxy_auth_hdr] = headers[proxy_auth_hdr]
  File "C:\Python34\lib\http\client.py", line 1088, in request
    def request(self, method, url, body=None, headers={}):
  File "C:\Python34\lib\http\client.py", line 1126, in _send_request
    # default charset of iso-8859-1.
  File "C:\Python34\lib\http\client.py", line 1084, in endheaders
    else:
  File "C:\Python34\lib\http\client.py", line 922, in _send_output
    msg += message_body
  File "C:\Python34\lib\http\client.py", line 857, in send
    if self.sock is None:
  File "C:\Python34\lib\http\client.py", line 834, in connect
    """Connect to the host and port specified in __init__."""
  File "C:\Python34\lib\socket.py", line 512, in create_connection

  File "C:\Python34\lib\socket.py", line 503, in create_connection
    except error as _:
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a
period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Z:\share_space\dataserv-client\dataserv_client\api.py", line 50, in _querry
  File "C:\Python34\lib\urllib\request.py", line 161, in urlopen
    """
  File "C:\Python34\lib\urllib\request.py", line 463, in open
    return response
  File "C:\Python34\lib\urllib\request.py", line 481, in _open
    if proto in ('http', 'https'):
  File "C:\Python34\lib\urllib\request.py", line 441, in _call_chain
    else:
  File "C:\Python34\lib\urllib\request.py", line 1210, in http_open

  File "C:\Python34\lib\urllib\request.py", line 1184, in do_open
    # server.
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not p
roperly respond after a period of time, or established connection failed because connected host has failed to respond>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dataserv-client.py", line 9, in <module>
  File "Z:\share_space\dataserv-client\dataserv_client\cli.py", line 123, in main
  File "Z:\share_space\dataserv-client\dataserv_client\api.py", line 95, in poll
  File "Z:\share_space\dataserv-client\dataserv_client\api.py", line 83, in ping
  File "Z:\share_space\dataserv-client\dataserv_client\api.py", line 68, in _querry
dataserv_client.exceptions.ConnectionError: Could not connect to server http://IPHERE!

**Comment by super3** [comment]
This should be fixed in the latest version. Please let us know if this error comes back.

**Comment by starsoccer** [comment]
Another crash has occured for me. Not sure if the issues are related in any way tho.
Below is the exact error
Traceback (most recent call last):
  File "C:\Python34\lib\urllib\request.py", line 1182, in do_open
    tunnel_headers[proxy_auth_hdr] = headers[proxy_auth_hdr]
  File "C:\Python34\lib\http\client.py", line 1088, in request
    def request(self, method, url, body=None, headers={}):
  File "C:\Python34\lib\http\client.py", line 1126, in _send_request
    # default charset of iso-8859-1.
  File "C:\Python34\lib\http\client.py", line 1084, in endheaders
    else:
  File "C:\Python34\lib\http\client.py", line 922, in _send_output
    msg += message_body
  File "C:\Python34\lib\http\client.py", line 857, in send
    if self.sock is None:
  File "C:\Python34\lib\http\client.py", line 834, in connect
    """Connect to the host and port specified in __init__."""
  File "C:\Python34\lib\socket.py", line 512, in create_connection

  File "C:\Python34\lib\socket.py", line 503, in create_connection
    except error as _:
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not
period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\dataserv-client\dataserv_client\api.py", line 68, in _url_query
  File "C:\Python34\lib\urllib\request.py", line 161, in urlopen
    """
  File "C:\Python34\lib\urllib\request.py", line 463, in open
    return response
  File "C:\Python34\lib\urllib\request.py", line 481, in _open
    if proto in ('http', 'https'):
  File "C:\Python34\lib\urllib\request.py", line 441, in _call_chain
    else:
  File "C:\Python34\lib\urllib\request.py", line 1210, in http_open

  File "C:\Python34\lib\urllib\request.py", line 1184, in do_open
    # server.
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the
roperly respond after a period of time, or established connection failed because connected hos

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dataserv-client", line 24, in <module>
  File "E:\dataserv-client\dataserv_client\cli.py", line 128, in main
  File "E:\dataserv-client\dataserv_client\api.py", line 116, in poll
  File "E:\dataserv-client\dataserv_client\api.py", line 104, in ping
  File "E:\dataserv-client\dataserv_client\api.py", line 89, in _url_query
  File "E:\dataserv-client\dataserv_client\api.py", line 68, in _url_query
  File "C:\Python34\lib\urllib\request.py", line 161, in urlopen
    """
  File "C:\Python34\lib\urllib\request.py", line 463, in open
    return response
  File "C:\Python34\lib\urllib\request.py", line 481, in _open
    if proto in ('http', 'https'):
  File "C:\Python34\lib\urllib\request.py", line 441, in _call_chain
    else:
  File "C:\Python34\lib\urllib\request.py", line 1210, in http_open

  File "C:\Python34\lib\urllib\request.py", line 1185, in do_open
    del headers[proxy_auth_hdr]
  File "C:\Python34\lib\http\client.py", line 1171, in getresponse

  File "C:\Python34\lib\http\client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "C:\Python34\lib\http\client.py", line 313, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Python34\lib\socket.py", line 374, in readinto
    raise
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not
period of time, or established connection failed because connected host has failed to respond
