### ISSUE TITLE
FarmerNotFound error on dataserv-client register

### ISSUE THREAD

**Issue by meecoder** [Storj/dataserv-client#71]
When I run dataserv-client register, I get this error (it's installed on Ubuntu)

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/messaging.py", line 46, in _url_query
    response = urllib.request.urlopen(req)
  File "/usr/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 469, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 507, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 587, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: NOT FOUND

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/dataserv-client", line 10, in <module>
    cli.main(sys.argv[1:])
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/cli.py", line 152, in main
    return getattr(client, command_name)(**arguments)
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/api.py", line 68, in register
    registered = self.messanger.register(self.cfg["payout_address"])
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/messaging.py", line 101, in register
    self.auth_address(), payout_addr
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/messaging.py", line 43, in _url_query
    headers = self._create_authentication_headers()
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/messaging.py", line 78, in _create_authentication_headers
    msg = self._get_node_address() + " " + header_date
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/messaging.py", line 71, in _get_node_address
    self._server_address = self.address()
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/messaging.py", line 92, in address
    data = self._url_query("/api/address", authenticate=False)
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/messaging.py", line 54, in _url_query
    raise exceptions.FarmerNotFound(self._server_url)
dataserv_client.exceptions.FarmerNotFound: Farmer not found at http://status.driveshare.org!

**Comment by F483** [comment]
@meecoder can you paste the exact commands you used?

**Comment by meecoder** [comment]
I ran 'dataserv-client register'

**Comment by meecoder** [comment]
if you mean to install i used 'sudo pip install git+https://github.com/Storj/dataserv-client' because the requirements.txt fix doesnt seem to be in the pip repo yet

**Comment by F483** [comment]
Its in the develop branch and well be merged into master with the next release (tonight).

**Comment by meecoder** [comment]
ok, any idea what could have caused the error though, thanks!

**Comment by F483** [comment]
Not yet. It may be a server side error.

**Comment by KLIM8D** [comment]
+1, I have the same problem with the client on FreeBSD.

I'm also experincing some weird behavior after upgrading to latest version. Using the poll command, the client is using a different address than what's specified in the config.
It results in the same HTTP 404 error as above though.

**Comment by KLIM8D** [comment]
Using the parameter `--url` seems to fix the issue
`dataserv-client --url=http://status.driveshare.org:5000`

However my client is still pinging with the wrong address.
`:~# dataserv-client --url=http://status.driveshare.org:5000 --config_path=.storj/config.json --debug poll
Pinging http://status.driveshare.org:5000 with address 1FtZd4hafBH4cDpbuXQBoHgoKA3px7UFU.
Pinging http://status.driveshare.org:5000 with address 1FtZd4hafBH4cDpbuXQBoHgoKA3px7UFU.`

`:~# cat ~/.storj/config.json
{"wallet": ".............", "version": "2.0.3", "payout_address": "1248oYrui9YsXWDKHffKQu6fDE2Q9cSHwp"}`

**Comment by F483** [comment]
The address listed is the authentication address and not the payout address. This should be changed to avoid confusion.

**Comment by KLIM8D** [comment]
This have been changed then. Just updated the client today from version 1.3 and in that version it was reporting the payout address executing the `poll` command.

Even though it's "working" now, neither of my addresses are listed on the status page (http://driveshare.org/status.html)

**Comment by F483** [comment]
The status page still lists the old clients/server as far as I know.

**Comment by F483** [comment]
I'm reopening a new issue for listing the correct address.
