### ISSUE TITLE
2.0.3: poll crashes if building is going on

### ISSUE THREAD

**Issue by unsystemizer** [Storj/dataserv-client#77]
* Start building in one terminal
* In another run `dataserv-client poll`

The client starts polling from the right address, but then it crashes. 

```
File "/usr/local/lib/python3.4/dist-packages/dataserv_client/messaging.py", line 45, in _url_query
    response = urllib.request.urlopen(req)
  File "/usr/lib/python3.4/urllib/request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: NOT FOUND

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/dataserv-client", line 10, in <module>
    cli.main(sys.argv[1:])
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/cli.py", line 153, in main
    return getattr(client, command_name)(**arguments)
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/api.py", line 135, in poll
    self.ping()
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/api.py", line 115, in ping
    self.messenger.ping()
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/messaging.py", line 110, in ping
    return self._url_query("/api/ping/%s" % self.auth_address())
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/messaging.py", line 42, in _url_query
    headers = self._create_authentication_headers()
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/messaging.py", line 77, in _create_authentication_headers
    msg = self._get_node_address() + " " + header_date
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/messaging.py", line 70, in _get_node_address
    self._server_address = self.address()
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/messaging.py", line 91, in address
    data = self._url_query("/api/address", authenticate=False)
  File "/usr/local/lib/python3.4/dist-packages/dataserv_client/messaging.py", line 53, in _url_query
    raise exceptions.FarmerNotFound(self._server_url)
dataserv_client.exceptions.FarmerNotFound: Farmer not found at http://status.driveshare.org!
```

**Comment by unsystemizer** [comment]
Seems duplicate of https://github.com/Storj/dataserv-client/issues/71
