### ISSUE TITLE
v 2.0.3 unable to register

### ISSUE THREAD

**Issue by JeremyPepper2** [Storj/dataserv-client#84]
On Mac OS X 10.10.5, unable to register.

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/dataserv_client/messaging.py", line 45, in _url_query
    response = urllib.request.urlopen(req)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 469, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 507, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 587, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: NOT FOUND

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/dataserv-client", line 10, in <module>
    cli.main(sys.argv[1:])
  File "/usr/local/lib/python3.4/site-packages/dataserv_client/cli.py", line 153, in main
    return getattr(client, command_name)(**arguments)
  File "/usr/local/lib/python3.4/site-packages/dataserv_client/api.py", line 72, in register
    registered = self.messenger.register(payout_address)
  File "/usr/local/lib/python3.4/site-packages/dataserv_client/messaging.py", line 100, in register
    self.auth_address(), payout_addr
  File "/usr/local/lib/python3.4/site-packages/dataserv_client/messaging.py", line 42, in _url_query
    headers = self._create_authentication_headers()
  File "/usr/local/lib/python3.4/site-packages/dataserv_client/messaging.py", line 77, in _create_authentication_headers
    msg = self._get_node_address() + " " + header_date
  File "/usr/local/lib/python3.4/site-packages/dataserv_client/messaging.py", line 70, in _get_node_address
    self._server_address = self.address()
  File "/usr/local/lib/python3.4/site-packages/dataserv_client/messaging.py", line 91, in address
    data = self._url_query("/api/address", authenticate=False)
  File "/usr/local/lib/python3.4/site-packages/dataserv_client/messaging.py", line 53, in _url_query
    raise exceptions.FarmerNotFound(self._server_url)
dataserv_client.exceptions.FarmerNotFound: Farmer not found at http://status.driveshare.org!

**Comment by F483** [comment]
For 2.0.0+ releases you whill have to use port 5000 for until we discontinue the older server/client. See https://github.com/Storj/dataserv-client/releases/tag/v2.0.3
